//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.30 at 12:24:32 AM WEST 
//


package com.aafonso.constituencyResults.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aafonso.xml.constituencyResults package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConstituencyName_QNAME = new QName("", "constituencyName");
    private final static QName _PartyCode_QNAME = new QName("", "partyCode");
    private final static QName _Share_QNAME = new QName("", "share");
    private final static QName _ConsituencyId_QNAME = new QName("", "consituencyId");
    private final static QName _Votes_QNAME = new QName("", "votes");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aafonso.xml.constituencyResults
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link ConstituencyResult }
     * 
     */
    public ConstituencyResult createConstituencyResult() {
        return new ConstituencyResult();
    }

    /**
     * Create an instance of {@link ConstituencyResults }
     * 
     */
    public ConstituencyResults createConstituencyResults() {
        return new ConstituencyResults();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "constituencyName")
    public JAXBElement<String> createConstituencyName(String value) {
        return new JAXBElement<String>(_ConstituencyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "partyCode")
    public JAXBElement<String> createPartyCode(String value) {
        return new JAXBElement<String>(_PartyCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "share")
    public JAXBElement<String> createShare(String value) {
        return new JAXBElement<String>(_Share_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "consituencyId")
    public JAXBElement<String> createConsituencyId(String value) {
        return new JAXBElement<String>(_ConsituencyId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "votes")
    public JAXBElement<String> createVotes(String value) {
        return new JAXBElement<String>(_Votes_QNAME, String.class, null, value);
    }

}
